[package]
name = "talk-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
log = "0.4.27"
proc-macro2 = { version = "1.0.95", features = ["nightly"] }
quote = "1.0.40"
syn = { version = "2.0.101", features = ["full"] }